# This is a basic workflow to help you get started with Actions

name: checking review system
on:
  push:
    branches: main
jobs:
  DEV:
    runs-on: self-hosted
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.1.jh1
        with:
          github_token: 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
        
        
       # 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
        
      #- name: Semantic versioning
      #  uses: paulhatch/semantic-version@v5.0.2
       # with:
        #  branch: main
         # tag_prefix: "v"
          ##inor_changes: "feat:"
          f#ormat: "v${major}.${minor}.${patch}-prerelease${increment}"
          
      - name: say something
        run: mkdir Dev
  
  QA:
    runs-on: self-hosted
    environment: QA
    needs: DEV
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: say something
        run: mkdir QA
      
  Pre-pod:
    runs-on: self-hosted
    environment: Pre-pod
    needs: QA
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: say something
        run: mkdir pre-prod
     
     
     
          



