# This is a basic workflow to help you get started with Actions

name: checking review system
on:
  push:
    branches: main
jobs:
  DEV:
    runs-on: self-hosted
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
       # 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
        
      #- name: Semantic versioning
      #  uses: paulhatch/semantic-version@v5.0.2
       # with:
        #  branch: main
         # tag_prefix: "v"
          ##inor_changes: "feat:"
          
      - name: create dev fol
        run: mkdir Dev
  
  QA:
    runs-on: self-hosted
    environment: QA
    needs: DEV
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: create QA folder
        run: mkdir QA
      
  Pre-pod:
    runs-on: self-hosted
    environment: Pre-pod
    needs: QA
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: create pre-prod folder
        run: mkdir pre-prod
     
     
     
          



