# This is a basic workflow to help you get started with Actions

name: checking review system
on:
  push:
    branches: main
jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: say something
        run: echo "hello world, This is Dev Environment"
  
  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: say something
        run: echo "hello world, This is QA Environment"
      
  Pre-pod:
    runs-on: ubuntu-latest
    environment: Pre-pod
    needs: QA
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: say something
        run: echo "hello world, This is Pre-pod Environment"
     
     
     
          



