# This is a basic workflow to help you get started with Actions

name: checking review system
on:
  push:
    branches: main
jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        
      - name: Semantic versioning
        uses: paulhatch/semantic-version@v5.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_changes: "feat:"
          format: "v${major}.${minor}.${patch}-release${increment}"
          
      - name: say something
        run: echo "hello world, This is Dev Environment - lets check"
  
  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: say something
        run: echo "hello world, This is QA Environment"
      
  Pre-pod:
    runs-on: ubuntu-latest
    environment: Pre-pod
    needs: QA
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: say something
        run: echo "hello world, This is Pre-pod Environment"
     
     
     
          



