# This is a basic workflow to help you get started with Actions

name: checking review system
on:
  workflow_dispatch:
jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: say something
        run: echo "hello, world"
  
  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: say something
        run: echo "hello, world"
     
     
     
          



